object Collections {
  val a = "12d334-8".filter(_.isDigit).map(_-'0').sum
//val b = List(1,2,-1,3,-6,4)...
//val c = """sc.l."""...
//val d = (1 to 10)...
//val e = List(Some(1), Some(0), None, Some(2), Some(-1))...
//val f = List(Left(1), Right(3), Left(2))...
//val g = (1 to 10)...
//val h = (1 to 10)...
//val i = (1 to 10)...
//val j = (1 to 10)...
//val k = List(1,2,-1,3,-6,4)...
//val l = "To be or not to be".split(" ")...
}
